name: ledger_l
description: "Wallet for transaction"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.8
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.4.4
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/icons/
   - assets/logos/
   - assets/flags/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

